// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// configurations of application for Admin
export const REPLACE_CONFIGURATIONS_PUBLIC = 'REPLACE_CONFIGURATIONS_PUBLIC'
export const REPLACE_CONFIGURATIONS = 'REPLACE_CONFIGURATIONS'
export const REPLACE_LOADING_CONFIGURATIONS = 'REPLACE_LOADING_CONFIGURATIONS'
export const REPLACE_NAME_CURRENCY = 'REPLACE_NAME_CURRENCY'

// primary drawer
export const REPLACE_PRIMARY_DRAWER = 'REPLACE_PRIMARY_DRAWER'

// wallet
export const REPLACE_TRANSACTIONS = 'REPLACE_TRANSACTIONS'
export const REPLACE_LOADING_TRANSACTIONS = 'REPLACE_LOADING_TRANSACTIONS'

// countries
export const REPLACE_LOADING_COUNTRIES = 'REPLACE_LOADING_COUNTRIES'
export const REPLACE_COUNTRIES = 'REPLACE_COUNTRIES'

// modals of the web
export const REPLACE_SHOW_MODAL_REGISTER = 'REPLACE_SHOW_MODAL_REGISTER'
export const REPLACE_SHOW_MODAL_PURCHASE_SERVICE = 'REPLACE_SHOW_MODAL_PURCHASE_SERVICE'
export const REPLACE_PLAN_SELECTED = 'REPLACE_PLAN_SELECTED'
export const REPLACE_SERVICE_SELECTED = 'REPLACE_SERVICE_SELECTED'
export const REPLACE_SHOW_MODAL_FORGOT_PASSWORD = 'REPLACE_SHOW_MODAL_FORGOT_PASSWORD'

// users
export const REPLACE_SHOW_MODAL_LOGIN = 'REPLACE_SHOW_MODAL_LOGIN'
export const REPLACE_SHOW_MODAL_REQUEST_RETIREMENT = 'REPLACE_SHOW_MODAL_REQUEST_RETIREMENT'
export const REPLACE_SHOW_MODAL_SUBSCRIPTION = 'REPLACE_SHOW_MODAL_SUBSCRIPTION'
export const REPLACE_SHOW_MODAL_UNSUBSCRIBE = 'REPLACE_SHOW_MODAL_UNSUBSCRIBE'
export const REPLACE_SHOW_MODAL_UPDATE_NETELLER_ACCOUNTS = 'REPLACE_SHOW_MODAL_UPDATE_NETELLER_ACCOUNTS'
export const REPLACE_LOADING_USERS = 'REPLACE_LOADING_USERS'
export const REPLACE_USERS = 'REPLACE_USERS'
export const REPLACE_SHOW_MODAL_DELETE_USER = 'REPLACE_SHOW_MODAL_DELETE_USER'
export const REPLACE_CURRENT_USER = 'REPLACE_CURRENT_USER'
export const REPLACE_LOADING_CURRENT_USER = 'REPLACE_LOADING_CURRENT_USER'
export const REPLACE_PURCHASES_BY_USER = 'REPLACE_PURCHASES_BY_USER'
export const REPLACE_LOADING_PURCHASES_BY_USER = 'REPLACE_LOADING_PURCHASES_BY_USER'
export const REPLACE_LOADING_SUBSCRIPTIONS_BY_USER = 'REPLACE_LOADING_SUBSCRIPTIONS_BY_USER'
export const REPLACE_SUBSCRIPTIONS_BY_USER = 'REPLACE_SUBSCRIPTIONS_BY_USER'
export const REPLACE_USER_CAN_TAKE_MONEY = 'REPLACE_USER_CAN_TAKE_MONEY'

// banners
export const REPLACE_LOADING_BANNERS = 'REPLACE_LOADING_BANNERS'
export const REPLACE_BANNERS = 'REPLACE_BANNERS'
export const REPLACE_LOADING_CURRENT_BANNER = 'REPLACE_LOADING_CURRENT_BANNER'
export const REPLACE_CURRENT_BANNER = 'REPLACE_CURRENT_BANNER'
export const REPLACE_SHOW_MODAL_DELETE_BANNER = 'REPLACE_SHOW_MODAL_DELETE_BANNER'

// plans
export const REPLACE_PLANS = 'REPLACE_PLANS'
export const REPLACE_LOADING_PLANS = 'REPLACE_LOADING_PLANS'
export const REPLACE_LOADING_PLANS_FOR_MEMBERSHIPS = 'REPLACE_LOADING_PLANS_FOR_MEMBERSHIPS'
export const REPLACE_PLANS_FOR_MEMBERSHIPS = 'REPLACE_PLANS_FOR_MEMBERSHIPS'
export const REPLACE_LOADING_CURRENT_PLAN = 'REPLACE_LOADING_CURRENT_PLAN'
export const REPLACE_CURRENT_PLAN = 'REPLACE_CURRENT_PLAN'

// services
export const REPLACE_SERVICES = 'REPLACE_SERVICES'
export const REPLACE_LOADING_SERVICES = 'REPLACE_LOADING_SERVICES'

// credits
export const REPLACE_CREDITS = 'REPLACE_CREDITS'
export const REPLACE_LOADING_CREDITS = 'REPLACE_LOADING_CREDITS'
export const REPLACE_CURRENT_CREDIT = 'REPLACE_CURRENT_CREDIT'
export const REPLACE_SHOW_MODAL_SUCCESS_CREDIT = 'REPLACE_SHOW_MODAL_SUCCESS_CREDIT'
export const REPLACE_SHOW_MODAL_INCREASE_DECREASE_CREDITS = 'REPLACE_SHOW_MODAL_INCREASE_DECREASE_CREDITS'

// purchases
export const REPLACE_LOADING_PURCHASES = 'REPLACE_LOADING_PURCHASES'
export const REPLACE_PURCHASES = 'REPLACE_PURCHASES'
export const REPLACE_STATE_PURCHASES = 'REPLACE_STATE_PURCHASES'
export const REPLACE_LOADING_STATE_PURCHASES = 'REPLACE_LOADING_STATE_PURCHASES'
export const REPLACE_SHOW_MODAL_CONFIRMATION_CHANGE_STATE = 'REPLACE_SHOW_MODAL_CONFIRMATION_CHANGE_STATE'
export const REPLACE_PURCHASE_SELECTED = 'REPLACE_PURCHASE_SELECTED'
export const REPLACE_STATE_PURCHASE_SELECTED = 'REPLACE_STATE_PURCHASE_SELECTED'
export const REPLACE_SHOW_MODAL_CHANGE_REFEREE_ID = 'REPLACE_SHOW_MODAL_CHANGE_REFEREE_ID'

// dashboard
export const REPLACE_DASHBOARD_PURCHASES = 'REPLACE_DASHBOARD_PURCHASES'
export const REPLACE_LOADING_DASHBOARD_PURCHASES = 'REPLACE_LOADING_DASHBOARD_PURCHASES'
export const REPLACE_DASHBOARD_USERS = 'REPLACE_DASHBOARD_USERS'
export const REPLACE_LOADING_DASHBOARD_USERS = 'REPLACE_LOADING_DASHBOARD_USERS'

// statistics
export const REPLACE_RETIREMENTS = 'REPLACE_RETIREMENTS'
export const REPLACE_LOADING_RETIREMENTS = 'REPLACE_LOADING_RETIREMENTS'
export const REPLACE_SHOW_MODAL_UPLOAD_SCREENSHOT = 'REPLACE_SHOW_MODAL_UPLOAD_SCREENSHOT'

// subscriptions
export const REPLACE_SUBSCRIPTIONS_NOT_CURRENT = 'REPLACE_SUBSCRIPTIONS_NOT_CURRENT'
export const REPLACE_LOADING_SUBSCRIPTIONS_NOT_CURRENT = 'REPLACE_LOADING_SUBSCRIPTIONS_NOT_CURRENT'
export const REPLACE_SUBSCRIPTION_CURRENT = 'REPLACE_SUBSCRIPTION_CURRENT'
export const REPLACE_LOADING_SUBSCRIPTIONS_CURRENT = 'REPLACE_LOADING_SUBSCRIPTIONS_CURRENT'
