// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// primary drawer
export const REPLACE_PRIMARY_DRAWER = 'REPLACE_PRIMARY_DRAWER'

// users
export const REPLACE_SHOW_MODAL_LOGIN = 'REPLACE_SHOW_MODAL_LOGIN'
export const REPLACE_SHOW_MODAL_REQUEST_RETIREMENT = 'REPLACE_SHOW_MODAL_REQUEST_RETIREMENT'
export const REPLACE_SHOW_MODAL_SUBSCRIPTION = 'REPLACE_SHOW_MODAL_SUBSCRIPTION'
export const REPLACE_SHOW_MODAL_UNSUBSCRIBE = 'REPLACE_SHOW_MODAL_UNSUBSCRIBE'
export const REPLACE_SHOW_MODAL_UPDATE_NETELLER_ACCOUNTS = 'REPLACE_SHOW_MODAL_UPDATE_NETELLER_ACCOUNTS'
export const REPLACE_LOADING_USERS = 'REPLACE_LOADING_USERS'
export const REPLACE_USERS = 'REPLACE_USERS'
export const REPLACE_SHOW_MODAL_DELETE_USER = 'REPLACE_SHOW_MODAL_DELETE_USER'
export const REPLACE_CURRENT_USER = 'REPLACE_CURRENT_USER'
export const REPLACE_LOADING_CURRENT_USER = 'REPLACE_LOADING_CURRENT_USER'
export const REPLACE_PURCHASES_BY_USER = 'REPLACE_PURCHASES_BY_USER'
export const REPLACE_LOADING_PURCHASES_BY_USER = 'REPLACE_LOADING_PURCHASES_BY_USER'
export const REPLACE_LOADING_SUBSCRIPTIONS_BY_USER = 'REPLACE_LOADING_SUBSCRIPTIONS_BY_USER'
export const REPLACE_SUBSCRIPTIONS_BY_USER = 'REPLACE_SUBSCRIPTIONS_BY_USER'
export const REPLACE_USER_CAN_TAKE_MONEY = 'REPLACE_USER_CAN_TAKE_MONEY'

//products
export const REPLACE_LOADING_PRODUCTS = 'REPLACE_LOADING_PRODUCTS'
export const REPLACE_PRODUCTS = 'REPLACE_PRODUCTS'
export const REPLACE_SHOW_MODAL_DELETE_PRODUCT = 'REPLACE_SHOW_MODAL_DELETE_PRODUCT'
export const REPLACE_CURRENT_PRODUCT = 'REPLACE_CURRENT_PRODUCT'
export const REPLACE_LOADING_CURRENT_PRODUCT = 'REPLACE_LOADING_CURRENT_PRODUCT'